using Investigation.ServerHub.Hubs;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;

namespace Investigation.ServerHub.Extensions
{
    public static class HubExtension
    {
        public static void MapAllHubs(this IEndpointRouteBuilder app)
        {
            app.MapHub<AdHub>("/adHub");
            app.MapHub<AdTargetHub>("/adTargetHub");
            app.MapHub<AboutHub>("/aboutHub");
            app.MapHub<AnnouncementCategoryHub>("/announcementCategoryHub");
            app.MapHub<AnnouncementHub>("/announcementHub");
            app.MapHub<AppRoleHub>("/appRoleHub");
            app.MapHub<AppUserHub>("/appUserHub");
            app.MapHub<AuditHub>("/auditHub");
            app.MapHub<BannerImageHub>("/bannerImageHub");
            app.MapHub<BlackListHub>("/blackListHub");
            app.MapHub<BlockedHub>("/blockedHub");
            app.MapHub<BlogHub>("/blogHub");  
            app.MapHub<BlogCategoryHub>("/blogCategoryHub");
            app.MapHub<CancelMembershipCategoryHub>("/cancelMembershipCategoryHub");
            app.MapHub<CancelMembershipHub>("/cancelMembershipHub");
            app.MapHub<CommentAnswerHub>("/commentAnswerHub");
            app.MapHub<CommentHub>("/commentHub");
            app.MapHub<CompanyHub>("/companyHub");
            app.MapHub<CompanyCategoryHub>("/companyCategoryHub");
            app.MapHub<CompanyContactHub>("/companyContactHub");
            app.MapHub<CompanyFinanceHub>("/companyFinanceHub");
            app.MapHub<CompanyPintechHub>("/companyPintechHub");
            app.MapHub<CompanyStageHub>("/companyStageHub");
            app.MapHub<CompanyTeamHub>("/companyTeamHub");
            app.MapHub<ContactHub>("/contactHub");
            app.MapHub<CountryHub>("/countryHub");
            app.MapHub<DataPolicyHub>("/dataPolicyHub");
            app.MapHub<EventsCategoryHub>("/eventsCategoryHub");
            app.MapHub<EventsHub>("/eventsHub");
            app.MapHub<EventsParticipantHub>("/eventsParticipantHub");
            app.MapHub<ExceptionLoggerHub>("/exceptionLoggerHub");
            app.MapHub<FrequentlyHub>("/frequentlyHub");
            app.MapHub<HitHub>("/hitHub");
            app.MapHub<HowItWorksHub>("/howItWorksHub");
            app.MapHub<InvestorHub>("/investorHub");
            app.MapHub<InvestorCategoryHub>("/investorCategoryHub");
            app.MapHub<KVKKHub>("/kvkkHub");
            app.MapHub<LayoutInfoHub>("/layoutInfoHub");
            app.MapHub<LogoHub>("/logoHub");
            app.MapHub<LikeHub>("/likeHub");
            app.MapHub<MessageHub>("/messageHub");
            app.MapHub<MessageUserBlockListHub>("/messageUserBlockListHub");
            app.MapHub<NewsHub>("/newsHub");
            app.MapHub<PersonalDataHub>("/personalDataHub");
            app.MapHub<PictureHub>("/pictureHub");
            app.MapHub<PostHub>("/postHub");
            app.MapHub<ProfileImageHub>("/profileImageHub");
            app.MapHub<QuestionOptionHub>("/questionOptionHub");
            app.MapHub<RecentlyInvestHub>("/recentlyInvestHub");
            app.MapHub<ReportCategoryHub>("/reportCategoryHub");
            app.MapHub<ReportHub>("/reportHub");            
            app.MapHub<SavedContentHub>("/savedContentHub"); 
            app.MapHub<SectorHub>("/sectorHub");
            app.MapHub<SectorNewsHub>("/sectorNewsHub");
            app.MapHub<SecuritySettingHub>("/securitySettingHub");
            app.MapHub<SendMessageHub>("/sendMessageHub");
            app.MapHub<SliderHub>("/sliderHub");
            app.MapHub<SocialMediaHub>("/socialMediaHub");
            app.MapHub<SubSectorHub>("/subSectorHub");
            app.MapHub<SurveyAnalyticsHub>("/surveyAnalyticsHub");
            app.MapHub<SurveyAnswerHub>("/surveyAnswerHub");
            app.MapHub<SurveyQuestionHub>("/surveyQuestionHub");
            app.MapHub<SurveyResponseHub>("/surveyResponseHub");
            app.MapHub<SurveyHub>("/surveyHub");
            app.MapHub<UserAgreementHub>("/userAgreementHub");
            app.MapHub<UserProfileImageHub>("/userProfileImageHub");
            app.MapHub<UserSessionHub>("/userSessionHub");
            app.MapHub<UserSocialMediaHub>("/userSocialMediaHub");
            app.MapHub<VisibilitySettingHub>("/visibilitySettingHub");
            app.MapHub<WhatWeOfferHub>("/whatWeOfferHub");
        }
    }
}
