<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <FrameworkReference Include="Microsoft.AspNetCore.App" />
	  <PackageReference Include="FluentValidation" Version="11.9.0" />
	  <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.0" />
	  <PackageReference Include="HtmlSanitizer" Version="9.0.892" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.ViewFeatures" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.11" />
    <PackageReference Include="NETCore.MailKit" Version="2.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="System.Threading.RateLimiting" Version="9.0.11" />
    <PackageReference Include="X.PagedList" Version="10.5.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Investigation.DataAccess\Investigation.DataAccess.csproj" />
    <ProjectReference Include="..\Investigation.Domain\Investigation.Domain.csproj" />
    <ProjectReference Include="..\Investigation.Shared\Investigation.Shared.csproj" />
  </ItemGroup>

</Project>
